theme: jekyll-theme-cayman
show_downloads : true

github :
   zip_url : https://github.com/ARDev1161/AmurClient/archive/refs/heads/master.zip
   tar_url : https://github.com/ARDev1161/AmurClient/archive/refs/heads/master.tar.gz
