.TH "modules/pwm Directory Reference" 3 "Sun Mar 19 2023" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules/pwm Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpwmcontroller\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpwmcontroller\&.h\fP"
.br
.ti -1c
.RI "file \fBpwmsettings\&.h\fP"
.br
.in -1c
