.TH "modules/registers/hc165 Directory Reference" 3 "Sun Nov 20 2022" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules/registers/hc165 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBhc165\&.cpp\fP"
.br
.ti -1c
.RI "file \fBhc165\&.h\fP"
.br
.ti -1c
.RI "file \fBtrain_hc165\&.cpp\fP"
.br
.in -1c
