.TH "logic Directory Reference" 3 "Mon Mar 20 2023" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmapping\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpilot\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpilot\&.h\fP"
.br
.in -1c
