.TH "modules/interfaces/uart Directory Reference" 3 "Mon Mar 20 2023" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules/interfaces/uart Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBuart\&.cpp\fP"
.br
.ti -1c
.RI "file \fBuart\&.h\fP"
.br
.in -1c
