.TH "modules/interfaces/spi Directory Reference" 3 "Tue Jun 21 2022" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules/interfaces/spi Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBspi\&.cpp\fP"
.br
.ti -1c
.RI "file \fBspi\&.h\fP"
.br
.in -1c
