.TH "modules Directory Reference" 3 "Sun Mar 19 2023" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBinterfaces\fP"
.br
.ti -1c
.RI "directory \fBpwm\fP"
.br
.ti -1c
.RI "directory \fBregisters\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBencoder\&.cpp\fP"
.br
.ti -1c
.RI "file \fBencoder\&.h\fP"
.br
.ti -1c
.RI "file \fBmotorcontroller\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmotorcontroller\&.h\fP"
.br
.ti -1c
.RI "file \fBperipheralcontroller\&.cpp\fP"
.br
.ti -1c
.RI "file \fBperipheralcontroller\&.h\fP"
.br
.ti -1c
.RI "file \fBperipheralsettings\&.h\fP"
.br
.in -1c
