.TH "ConfigProcessor" 3 "Sun Nov 20 2022" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigProcessor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <configprocessor\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigProcessor\fP (std::string \fBconfigName\fP)"
.br
.ti -1c
.RI "\fBConfigProcessor\fP ()"
.br
.ti -1c
.RI "int \fBsetOptionsConfig\fP ()"
.br
.ti -1c
.RI "int \fBread\fP (std::string \fBconfigName\fP)"
.br
.ti -1c
.RI "int \fBwrite\fP ()"
.br
.ti -1c
.RI "int \fBsearch\fP (std::string settingName, std::string &out)"
.br
.ti -1c
.RI "int \fBsearch\fP (std::string settingName, int &out)"
.br
.ti -1c
.RI "int \fBsearch\fP (std::string settingName, double &out)"
.br
.ti -1c
.RI "int \fBsearch\fP (std::string settingName, bool &out)"
.br
.ti -1c
.RI "int \fBrewrite\fP (std::string settingName, std::string value)"
.br
.ti -1c
.RI "int \fBrewrite\fP (std::string settingName, int value)"
.br
.ti -1c
.RI "int \fBrewrite\fP (std::string settingName, double value)"
.br
.ti -1c
.RI "int \fBrewrite\fP (std::string settingName, bool value)"
.br
.ti -1c
.RI "int \fBadd\fP (std::string settingName, std::string value)"
.br
.ti -1c
.RI "int \fBadd\fP (std::string settingName, int value)"
.br
.ti -1c
.RI "int \fBadd\fP (std::string settingName, double value)"
.br
.ti -1c
.RI "int \fBadd\fP (std::string settingName, bool value)"
.br
.ti -1c
.RI "void \fBgetRoot\fP ()"
.br
.ti -1c
.RI "std::string \fBgetConfigFilename\fP () const"
.br
.ti -1c
.RI "void \fBsetConfigFilename\fP (std::string newConfigName)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "std::vector< std::string > \fBsplitPath\fP (std::string path)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBconfigName\fP"
.br
.RI "Setuped config filename\&. "
.ti -1c
.RI "libconfig::Config \fBconfig\fP"
.br
.RI "Libconfig instance\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConfigProcessor::ConfigProcessor (std::string configName)"
Constructor with custom config filename\&. 
.PP
\fBParameters\fP
.RS 4
\fIfile\fP Config filename\&. 
.RE
.PP

.SS "ConfigProcessor::ConfigProcessor ()"
Constructor with default config filename\&. 
.SH "Member Function Documentation"
.PP 
.SS "int ConfigProcessor::add (std::string settingName, bool value)"

.SS "int ConfigProcessor::add (std::string settingName, double value)"

.SS "int ConfigProcessor::add (std::string settingName, int value)"

.SS "int ConfigProcessor::add (std::string settingName, std::string value)"

.SS "std::string ConfigProcessor::getConfigFilename () const"
Return config filename\&. 
.SS "void ConfigProcessor::getRoot ()"

.SS "int ConfigProcessor::read (std::string configName)"
Read configuration from file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfile\fP Config filename\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 if success\&. 1 if I/O or parse error\&. 
.RE
.PP

.SS "int ConfigProcessor::rewrite (std::string settingName, bool value)"
Write boolean parameter to configuration\&. 
.PP
\fBParameters\fP
.RS 4
\fIsettingName\fP Address of parameter in configuration\&. 
.br
\fIvalue\fP Value of parameter\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Code of execution\&. Normal - 0, if file not found - 1\&. 
.RE
.PP

.SS "int ConfigProcessor::rewrite (std::string settingName, double value)"
Write double parameter to configuration\&. 
.PP
\fBParameters\fP
.RS 4
\fIsettingName\fP Address of parameter in configuration\&. 
.br
\fIvalue\fP Value of parameter\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Code of execution\&. Normal - 0, if file not found - 1\&. 
.RE
.PP

.SS "int ConfigProcessor::rewrite (std::string settingName, int value)"
Write integer parameter to configuration\&. 
.PP
\fBParameters\fP
.RS 4
\fIsettingName\fP Address of parameter in configuration\&. 
.br
\fIvalue\fP Value of parameter\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Code of execution\&. Normal - 0, if file not found - 1\&. 
.RE
.PP

.SS "int ConfigProcessor::rewrite (std::string settingName, std::string value)"
Write string parameter to configuration\&. 
.PP
\fBParameters\fP
.RS 4
\fIsettingName\fP Address of parameter in configuration\&. 
.br
\fIvalue\fP Value of parameter\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Code of execution\&. Normal - 0, if file not found - 1\&. 
.RE
.PP

.SS "int ConfigProcessor::search (std::string settingName, bool & out)"
Get bool parameter from configuration\&. param[in] settingName Address of parameter in configuration\&. 
.PP
\fBParameters\fP
.RS 4
\fIout\fP Value of parameter\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Code of execution\&. Normal - 0, if file not found - 1\&. 
.RE
.PP

.SS "int ConfigProcessor::search (std::string settingName, double & out)"
Get double parameter from configuration\&. 
.PP
\fBParameters\fP
.RS 4
\fIsettingName\fP Address of parameter in configuration\&. 
.br
\fIout\fP Value of parameter\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Code of execution\&. Normal - 0, if file not found - 1\&. 
.RE
.PP

.SS "int ConfigProcessor::search (std::string settingName, int & out)"
Get integer parameter from configuration\&. 
.PP
\fBParameters\fP
.RS 4
\fIsettingName\fP Address of parameter in configuration\&. 
.br
\fIout\fP Value of parameter\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Code of execution\&. Normal - 0, if file not found - 1\&. 
.RE
.PP

.SS "int ConfigProcessor::search (std::string settingName, std::string & out)"
Get string parameter from configuration\&. 
.PP
\fBParameters\fP
.RS 4
\fIsettingName\fP Address of parameter in configuration\&. 
.br
\fIout\fP Value of parameter\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Code of execution\&. Normal - 0, if file not found - 1\&. 
.RE
.PP

.SS "void ConfigProcessor::setConfigFilename (std::string newConfigName)"
Setup config filename\&. 
.SS "int ConfigProcessor::setOptionsConfig ()"
Initialize libconfig\&. 
.PP
\fBParameters\fP
.RS 4
\fIfile\fP Config filename\&. 
.RE
.PP

.SS "std::vector<std::string> ConfigProcessor::splitPath (std::string path)\fC [private]\fP"

.SS "int ConfigProcessor::write ()"
Write configuration to file\&. 
.PP
\fBReturns\fP
.RS 4
0 if success\&. 1 if I/O error\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "libconfig::Config ConfigProcessor::config\fC [private]\fP"

.PP
Libconfig instance\&. 
.SS "std::string ConfigProcessor::configName\fC [private]\fP"

.PP
Setuped config filename\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
