.TH "modules/registers/hc165/hc165.h" 3 "Tue Jun 21 2022" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules/registers/hc165/hc165.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./registerssettings\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHC165\fP"
.br
.RI "Класс работы с регистром 74\fBHC165\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
