.TH "logiccontroller.h" 3 "Sun Nov 20 2022" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logiccontroller.h
.SH SYNOPSIS
.br
.PP
\fC#include <iomanip>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include 'modules/peripheralcontroller\&.h'\fP
.br
\fC#include 'network/networkcontroller\&.h'\fP
.br
\fC#include 'configprocessor\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLogicController\fP"
.br
.RI "Класс логики управления роботом "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
