.TH "md_CHANGELOG" 3 "Mon Mar 20 2023" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_CHANGELOG \- v0\&.88\&.43 (2023-03-19) 

.SS "Refactor"
.IP "\(bu" 2
\fB\fBConfigProcessor\fP\fP: Renamed functions
.IP "\(bu" 2
\fB\fBConfigProcessor\fP\fP: Refactored code in config processor & logic controller
.PP
.SH "v0\&.88\&.42 (2021-07-20)"
.PP
.SH "v0\&.88 (2020-11-30)"
.PP

