.TH "modules/motorcontroller.h" 3 "Sun Nov 20 2022" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules/motorcontroller.h
.SH SYNOPSIS
.br
.PP
\fC#include 'encoder\&.h'\fP
.br
\fC#include 'peripheralsettings\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMotor\fP"
.br
.ti -1c
.RI "class \fBMotorController\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
