.TH "PeripheralSettings" 3 "Sun Mar 19 2023" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PeripheralSettings \- Структура для хранения пинов и настроек оборудования периферии  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <peripheralsettings\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEncoderSettings\fP \fBencoderSettings\fP"
.br
.ti -1c
.RI "\fBMotorSettings\fP \fBmotorSettings\fP"
.br
.ti -1c
.RI "\fBRegisterSettings\fP \fBregisterSettings\fP"
.br
.ti -1c
.RI "\fBPWMPins\fP \fBpwmSettings\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Структура для хранения пинов и настроек оборудования периферии 

Данная структура хранит набор пинов и настроек оборудования периферии\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBEncoderSettings\fP PeripheralSettings::encoderSettings"

.SS "\fBMotorSettings\fP PeripheralSettings::motorSettings"

.SS "\fBPWMPins\fP PeripheralSettings::pwmSettings"

.SS "\fBRegisterSettings\fP PeripheralSettings::registerSettings"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
