.TH "modules/registers/registerssettings.h" 3 "Sun Nov 20 2022" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules/registers/registerssettings.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRegisterSettings\fP"
.br
.RI "Структура для хранения параметров регистров "
.ti -1c
.RI "struct \fBRegisterSettings::General\fP"
.br
.RI "Общие настройки регистров\&. "
.ti -1c
.RI "struct \fBRegisterSettings::HC595Pins\fP"
.br
.RI "Структура для хранения пинов выходного регистра "
.ti -1c
.RI "struct \fBRegisterSettings::HC165Pins\fP"
.br
.RI "Структура для хранения пинов входного регистра "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
