.TH "RegisterSettings::HC165Pins" 3 "Mon Mar 20 2023" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RegisterSettings::HC165Pins \- Структура для хранения пинов входного регистра  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <registerssettings\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBdataPin\fP = 4"
.br
.ti -1c
.RI "const int \fBclkPin\fP = 17"
.br
.ti -1c
.RI "const int \fBclkInhibitePin\fP = 22"
.br
.ti -1c
.RI "const int \fBloadPin\fP = 27"
.br
.in -1c
.SH "Detailed Description"
.PP 
Структура для хранения пинов входного регистра 

Данная структура хранит набор пинов Raspberry Pi для управления входным регистром 74\fBHC165\fP в нотации GPIO\&. 
.SH "Member Data Documentation"
.PP 
.SS "const int RegisterSettings::HC165Pins::clkInhibitePin = 22"

.SS "const int RegisterSettings::HC165Pins::clkPin = 17"

.SS "const int RegisterSettings::HC165Pins::dataPin = 4"

.SS "const int RegisterSettings::HC165Pins::loadPin = 27"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
