.TH "modules/registers/registercontroller.h" 3 "Mon Mar 20 2023" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules/registers/registercontroller.h
.SH SYNOPSIS
.br
.PP
\fC#include 'hc595/hc595\&.h'\fP
.br
\fC#include 'hc165/hc165\&.h'\fP
.br
\fC#include 'registerssettings\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRegisterController\fP"
.br
.RI "Класс контроллера регистров "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
