.TH "rewriteSetting" 3 "Sun Mar 19 2023" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rewriteSetting
.SH SYNOPSIS
.br
.PP
.PP
Inherits testing::Test\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.ti -1c
.RI "void \fBTearDown\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBConfigProcessor\fP * \fBconfig\fP"
.br
.ti -1c
.RI "fs::path \fBfilepath\fP"
.br
.ti -1c
.RI "std::string \fBvalueString\fP = 'string'"
.br
.ti -1c
.RI "int \fBvalueInt\fP = 42"
.br
.ti -1c
.RI "float \fBvalueFloat\fP = 0\&.42"
.br
.ti -1c
.RI "bool \fBvalueBool\fP = true"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void rewriteSetting::SetUp ()\fC [inline]\fP, \fC [protected]\fP"

.SS "void rewriteSetting::TearDown ()\fC [inline]\fP, \fC [protected]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBConfigProcessor\fP* rewriteSetting::config\fC [protected]\fP"

.SS "fs::path rewriteSetting::filepath\fC [protected]\fP"

.SS "bool rewriteSetting::valueBool = true\fC [protected]\fP"

.SS "float rewriteSetting::valueFloat = 0\&.42\fC [protected]\fP"

.SS "int rewriteSetting::valueInt = 42\fC [protected]\fP"

.SS "std::string rewriteSetting::valueString = 'string'\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
