.TH "searchSetting" 3 "Mon Mar 20 2023" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
searchSetting
.SH SYNOPSIS
.br
.PP
.PP
Inherits testing::Test\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.ti -1c
.RI "void \fBTearDown\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBConfigProcessor\fP * \fBconfig\fP"
.br
.ti -1c
.RI "fs::path \fBfilepath\fP"
.br
.ti -1c
.RI "std::string \fBoutString\fP"
.br
.ti -1c
.RI "int \fBoutInt\fP"
.br
.ti -1c
.RI "float \fBoutFloat\fP"
.br
.ti -1c
.RI "bool \fBoutBool\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void searchSetting::SetUp ()\fC [inline]\fP, \fC [protected]\fP"

.SS "void searchSetting::TearDown ()\fC [inline]\fP, \fC [protected]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBConfigProcessor\fP* searchSetting::config\fC [protected]\fP"

.SS "fs::path searchSetting::filepath\fC [protected]\fP"

.SS "bool searchSetting::outBool\fC [protected]\fP"

.SS "float searchSetting::outFloat\fC [protected]\fP"

.SS "int searchSetting::outInt\fC [protected]\fP"

.SS "std::string searchSetting::outString\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
