.TH "network/server.h" 3 "Thu Jul 8 2021" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
network/server.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <grpcpp/grpcpp\&.h>\fP
.br
\fC#include <grpcpp/health_check_service_interface\&.h>\fP
.br
\fC#include <grpcpp/ext/proto_server_reflection_plugin\&.h>\fP
.br
\fC#include 'protobuf/amur\&.grpc\&.pb\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgrpcServer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
