.TH "SPI" 3 "Tue Jun 21 2022" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI \- Класс работы с интерфейсом \fBSPI\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spi\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSPI\fP ()"
.br
.ti -1c
.RI "int \fBinit\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static const int \fBCHANNEL\fP = 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Класс работы с интерфейсом \fBSPI\fP\&. 

Данный класс инкапсулирует взаимодействие с интерфейсом \fBSPI\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SPI::SPI ()"
Создаёт экземпляр класса для работы с интерфейсом \fBI2C\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "int SPI::init ()"
Инициирует работу с интерфейсом \fBSPI\fP\&. 
.PP
\fBReturns\fP
.RS 4
Возвращает 0 если удалось открыть порт 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "const int SPI::CHANNEL = 1\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
