.TH "timer/Timer.h" 3 "Thu Jul 8 2021" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timer/Timer.h
.SH SYNOPSIS
.br
.PP
\fC#include <chrono>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <thread>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTimer\fP"
.br
.RI "\fBTimer\fP class, wrapper around the POSIX per-process timer\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
