.TH "modules/registers/hc165/train_hc165.cpp" 3 "Sun Mar 19 2023" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules/registers/hc165/train_hc165.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'hc165\&.h'\fP
.br
\fC#include '\&.\&./registerssettings\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFREQ_PIN\fP   10"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FREQ_PIN   10"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
