.TH "UART" 3 "Sun Mar 19 2023" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UART \- Класс работы с интерфейсом \fBUART\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uart\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUART\fP ()"
.br
.ti -1c
.RI "int \fBinit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Класс работы с интерфейсом \fBUART\fP\&. 

Данный класс инкапсулирует взаимодействие с интерфейсом \fBUART\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UART::UART ()"
Создаёт экземпляр класса для работы с интерфейсом \fBUART\fP\&. 
.SH "Member Function Documentation"
.PP 
.SS "int UART::init ()"
Инициирует работу с интерфейсом \fBUART\fP\&. 
.PP
\fBReturns\fP
.RS 4
Возвращает 0 если удалось открыть порт 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
