.TH "modules/interfaces/uart/uart.h" 3 "Mon Mar 20 2023" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules/interfaces/uart/uart.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUART\fP"
.br
.RI "Класс работы с интерфейсом \fBUART\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
