.TH "logic/mapping/vector2.h" 3 "Sun Nov 20 2022" "Version 0.42" "AmurClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logic/mapping/vector2.h
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVector2\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AmurClient from the source code\&.
