// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: amur.proto
#ifndef GRPC_amur_2eproto__INCLUDED
#define GRPC_amur_2eproto__INCLUDED

#include "amur.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace AMUR {

class Maintenance final {
 public:
  static constexpr char const* service_full_name() {
    return "AMUR.Maintenance";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Unary exchange
    virtual ::grpc::Status DataExchange(::grpc::ClientContext* context, const ::AMUR::AmurSensors& request, ::AMUR::AmurControls* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AMUR::AmurControls>> AsyncDataExchange(::grpc::ClientContext* context, const ::AMUR::AmurSensors& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AMUR::AmurControls>>(AsyncDataExchangeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AMUR::AmurControls>> PrepareAsyncDataExchange(::grpc::ClientContext* context, const ::AMUR::AmurSensors& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::AMUR::AmurControls>>(PrepareAsyncDataExchangeRaw(context, request, cq));
    }
    // Bidirectional stream
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::AMUR::AmurSensors, ::AMUR::AmurControls>> DataStreamExchange(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::AMUR::AmurSensors, ::AMUR::AmurControls>>(DataStreamExchangeRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::AMUR::AmurSensors, ::AMUR::AmurControls>> AsyncDataStreamExchange(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::AMUR::AmurSensors, ::AMUR::AmurControls>>(AsyncDataStreamExchangeRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::AMUR::AmurSensors, ::AMUR::AmurControls>> PrepareAsyncDataStreamExchange(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::AMUR::AmurSensors, ::AMUR::AmurControls>>(PrepareAsyncDataStreamExchangeRaw(context, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Unary exchange
      virtual void DataExchange(::grpc::ClientContext* context, const ::AMUR::AmurSensors* request, ::AMUR::AmurControls* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void DataExchange(::grpc::ClientContext* context, const ::AMUR::AmurSensors* request, ::AMUR::AmurControls* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void DataExchange(::grpc::ClientContext* context, const ::AMUR::AmurSensors* request, ::AMUR::AmurControls* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Bidirectional stream
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void DataStreamExchange(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::AMUR::AmurSensors,::AMUR::AmurControls>* reactor) = 0;
      #else
      virtual void DataStreamExchange(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::AMUR::AmurSensors,::AMUR::AmurControls>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AMUR::AmurControls>* AsyncDataExchangeRaw(::grpc::ClientContext* context, const ::AMUR::AmurSensors& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::AMUR::AmurControls>* PrepareAsyncDataExchangeRaw(::grpc::ClientContext* context, const ::AMUR::AmurSensors& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::AMUR::AmurSensors, ::AMUR::AmurControls>* DataStreamExchangeRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::AMUR::AmurSensors, ::AMUR::AmurControls>* AsyncDataStreamExchangeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::AMUR::AmurSensors, ::AMUR::AmurControls>* PrepareAsyncDataStreamExchangeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status DataExchange(::grpc::ClientContext* context, const ::AMUR::AmurSensors& request, ::AMUR::AmurControls* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AMUR::AmurControls>> AsyncDataExchange(::grpc::ClientContext* context, const ::AMUR::AmurSensors& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AMUR::AmurControls>>(AsyncDataExchangeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AMUR::AmurControls>> PrepareAsyncDataExchange(::grpc::ClientContext* context, const ::AMUR::AmurSensors& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::AMUR::AmurControls>>(PrepareAsyncDataExchangeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::AMUR::AmurSensors, ::AMUR::AmurControls>> DataStreamExchange(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::AMUR::AmurSensors, ::AMUR::AmurControls>>(DataStreamExchangeRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::AMUR::AmurSensors, ::AMUR::AmurControls>> AsyncDataStreamExchange(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::AMUR::AmurSensors, ::AMUR::AmurControls>>(AsyncDataStreamExchangeRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::AMUR::AmurSensors, ::AMUR::AmurControls>> PrepareAsyncDataStreamExchange(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::AMUR::AmurSensors, ::AMUR::AmurControls>>(PrepareAsyncDataStreamExchangeRaw(context, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void DataExchange(::grpc::ClientContext* context, const ::AMUR::AmurSensors* request, ::AMUR::AmurControls* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void DataExchange(::grpc::ClientContext* context, const ::AMUR::AmurSensors* request, ::AMUR::AmurControls* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void DataExchange(::grpc::ClientContext* context, const ::AMUR::AmurSensors* request, ::AMUR::AmurControls* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void DataStreamExchange(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::AMUR::AmurSensors,::AMUR::AmurControls>* reactor) override;
      #else
      void DataStreamExchange(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::AMUR::AmurSensors,::AMUR::AmurControls>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::AMUR::AmurControls>* AsyncDataExchangeRaw(::grpc::ClientContext* context, const ::AMUR::AmurSensors& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::AMUR::AmurControls>* PrepareAsyncDataExchangeRaw(::grpc::ClientContext* context, const ::AMUR::AmurSensors& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::AMUR::AmurSensors, ::AMUR::AmurControls>* DataStreamExchangeRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::AMUR::AmurSensors, ::AMUR::AmurControls>* AsyncDataStreamExchangeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::AMUR::AmurSensors, ::AMUR::AmurControls>* PrepareAsyncDataStreamExchangeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DataExchange_;
    const ::grpc::internal::RpcMethod rpcmethod_DataStreamExchange_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Unary exchange
    virtual ::grpc::Status DataExchange(::grpc::ServerContext* context, const ::AMUR::AmurSensors* request, ::AMUR::AmurControls* response);
    // Bidirectional stream
    virtual ::grpc::Status DataStreamExchange(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::AMUR::AmurControls, ::AMUR::AmurSensors>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_DataExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DataExchange() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DataExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataExchange(::grpc::ServerContext* /*context*/, const ::AMUR::AmurSensors* /*request*/, ::AMUR::AmurControls* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDataExchange(::grpc::ServerContext* context, ::AMUR::AmurSensors* request, ::grpc::ServerAsyncResponseWriter< ::AMUR::AmurControls>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DataStreamExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DataStreamExchange() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_DataStreamExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataStreamExchange(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::AMUR::AmurControls, ::AMUR::AmurSensors>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDataStreamExchange(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::AMUR::AmurControls, ::AMUR::AmurSensors>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DataExchange<WithAsyncMethod_DataStreamExchange<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_DataExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_DataExchange() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::AMUR::AmurSensors, ::AMUR::AmurControls>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::AMUR::AmurSensors* request, ::AMUR::AmurControls* response) { return this->DataExchange(context, request, response); }));}
    void SetMessageAllocatorFor_DataExchange(
        ::grpc::experimental::MessageAllocator< ::AMUR::AmurSensors, ::AMUR::AmurControls>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::AMUR::AmurSensors, ::AMUR::AmurControls>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_DataExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataExchange(::grpc::ServerContext* /*context*/, const ::AMUR::AmurSensors* /*request*/, ::AMUR::AmurControls* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DataExchange(
      ::grpc::CallbackServerContext* /*context*/, const ::AMUR::AmurSensors* /*request*/, ::AMUR::AmurControls* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DataExchange(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::AMUR::AmurSensors* /*request*/, ::AMUR::AmurControls* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_DataStreamExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_DataStreamExchange() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::AMUR::AmurSensors, ::AMUR::AmurControls>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->DataStreamExchange(context); }));
    }
    ~ExperimentalWithCallbackMethod_DataStreamExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataStreamExchange(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::AMUR::AmurControls, ::AMUR::AmurSensors>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::AMUR::AmurSensors, ::AMUR::AmurControls>* DataStreamExchange(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::AMUR::AmurSensors, ::AMUR::AmurControls>* DataStreamExchange(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_DataExchange<ExperimentalWithCallbackMethod_DataStreamExchange<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_DataExchange<ExperimentalWithCallbackMethod_DataStreamExchange<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_DataExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DataExchange() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DataExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataExchange(::grpc::ServerContext* /*context*/, const ::AMUR::AmurSensors* /*request*/, ::AMUR::AmurControls* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DataStreamExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DataStreamExchange() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_DataStreamExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataStreamExchange(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::AMUR::AmurControls, ::AMUR::AmurSensors>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_DataExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DataExchange() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_DataExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataExchange(::grpc::ServerContext* /*context*/, const ::AMUR::AmurSensors* /*request*/, ::AMUR::AmurControls* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDataExchange(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DataStreamExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DataStreamExchange() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_DataStreamExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataStreamExchange(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::AMUR::AmurControls, ::AMUR::AmurSensors>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDataStreamExchange(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_DataExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_DataExchange() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DataExchange(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_DataExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataExchange(::grpc::ServerContext* /*context*/, const ::AMUR::AmurSensors* /*request*/, ::AMUR::AmurControls* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DataExchange(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DataExchange(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_DataStreamExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_DataStreamExchange() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->DataStreamExchange(context); }));
    }
    ~ExperimentalWithRawCallbackMethod_DataStreamExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DataStreamExchange(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::AMUR::AmurControls, ::AMUR::AmurSensors>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* DataStreamExchange(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* DataStreamExchange(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DataExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DataExchange() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::AMUR::AmurSensors, ::AMUR::AmurControls>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::AMUR::AmurSensors, ::AMUR::AmurControls>* streamer) {
                       return this->StreamedDataExchange(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DataExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DataExchange(::grpc::ServerContext* /*context*/, const ::AMUR::AmurSensors* /*request*/, ::AMUR::AmurControls* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDataExchange(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::AMUR::AmurSensors,::AMUR::AmurControls>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_DataExchange<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_DataExchange<Service > StreamedService;
};

}  // namespace AMUR


#endif  // GRPC_amur_2eproto__INCLUDED
