name: Doxygen

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build-documentation:
    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@v2
    
    # Build the HTML documentation
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.3.1
      with:
        working-directory: .
        doxyfile-path: ./Doxyfile
        additional-packages: font-fira-code
        enable-latex: true
